# -*- coding: utf-8 -*-
"""WshiperX说话人识别asr.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16QdcXq01vUlEjz3K0180sn8USksF1o7d
"""

!pip install yt-dlp

# ==========================================
# 单元格 1: 依赖环境一键全量安装
# ==========================================
print("⏳ 正在一键安装 WhisperX 顶级生产环境（请观察下方进度条...）")

print("\n📦 [1/3] 正在对齐兼容的标准的 PyTorch 运行环境...")
!pip install -U torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124

print("\n📦 [2/3] 正在从 GitHub 源码克隆并编译最新版 WhisperX 核心...")
!pip install git+https://github.com/m-bain/whisperX.git

print("\n📦 [3/3] 【核心修复】强行粉碎并降级 NumPy/Pandas 冲突版本...")
!pip install --force-reinstall "numpy<2.1" "pandas<2.4"

print("\n✨ WhisperX 环境依赖悉数安装成功！")
print("⚠️ 极重要提示：由于安装了底层 C++ 算子依赖，请务必点击顶部菜单：")
print("   'Runtime' (代码执行程序) -> 'Restart session' (重启会话)")
print("   重启只需 1 秒，重启后即可永久免安装，直接流畅运行下方的转写单元格。")

#@markdown ##**构建翻译命令**
#@markdown 保留时间戳
keep_timestamp = '是' #@param ['是','否']

#@markdown 模型名
model_name = "Agenes-free" #@param ["Qwen3-8B", "GLM-4-9B-0414","qwen2.5 7B API","XiaoMiMIMO","Hunyuan-MT-7B","Agenes-free"]

#@markdown 分段局数
segment_size = 11 #@param

#@markdown 并行工作线程数
num_workers = 4 #@param {type:"integer"}

# Function to generate and save the command
def generate_and_save_command(keep_timestamp,model_name,segment_size, num_workers):

    command = "python translator_app.py"

    if keep_timestamp == '是':
        command += " --keep"

    command += f' --api "{model_name}"'

    # Add the segment size argument if it's a positive integer
    if isinstance(segment_size, int) and segment_size > 0:
        command += f' --seg {segment_size}'

    # Add the number of workers argument
    if isinstance(num_workers, int) and num_workers > 0:
        command += f' --workers {num_workers}'

    command += ' --filepath "subtitles/word_level.txt"'


    with open("command.txt", "w") as f:
        f.write(command)

    print(f"Generated command: {command}")
    print("Command saved to command.txt")

generate_and_save_command(keep_timestamp,model_name,segment_size, num_workers)

# 使用官方脚本安装 Deno
!curl -fsSL https://deno.land/install.sh | sh

# 将 Deno 添加到环境变量 PATH 中
import os
os.environ['DENO_INSTALL'] = '/root/.deno'
os.environ['PATH'] += f":{os.environ['DENO_INSTALL']}/bin"

# 验证安装（打印版本号）
!deno --version

!rm -rf subtitles/*
!rm -rf audio/*

# Commented out IPython magic to ensure Python compatibility.
#@markdown ## **下载YouTube视频音频（仅音频）**
# %cd /content
import subprocess
import os
from google.colab import userdata
from pathlib import Path  # 添加这行导入Path类

# 参数设置
URL='https://www.youtube.com/watch?v=wUzt8baRKQ8' #@param {type:"string"}
IsUsingCookie = True #@param {type:'boolean'}

# 自动去除URL中的空格
URL = URL.strip()

# Cookies 处理逻辑
cookies_file_path = None
if IsUsingCookie:
    cookies_content = userdata.get('YT_COOKIES')
    if cookies_content:
        cookies_file_path = 'youtube_cookies.txt'
        with open(cookies_file_path, 'w', encoding='utf-8') as f:
            f.write(cookies_content)
        print("Cookies saved to youtube_cookies.txt")
    else:
        print("Warning: YT_COOKIES not found in environment variables. Proceeding without cookies.")
else:
    print("Proceeding without cookies.")

# 确保音频目录存在
audio_dir = '/content/audio'
os.makedirs(audio_dir, exist_ok=True)

# 构建命令 - 只下载音频
cmd = [
    'python', '-m', 'yt_dlp',
    '-x',                     # 提取音频（只下载音频，不下载视频）
    '--audio-format', 'mp3',  # 音频格式（可选：mp3, m4a, wav, best）
    '--audio-quality', '0',   # 0 是最好质量，VBR；或指定如 192K
    '--extractor-args', 'youtube:player_client=default,-web_safari', # 核心修复参数
    '--remote-components', 'ejs:github', # 核心修复参数
    '--print', 'after_move:%(filepath)s',  # 关键：输出最终文件路径用于捕获
    '-o', f'{audio_dir}/%(title)s.%(ext)s', # 输出路径
    URL
]

if cookies_file_path:
    cmd.extend(['--cookies', cookies_file_path])

video_path_local = None  # 初始化变量

try:
    print(f"正在下载音频: {URL}")
    # 运行命令并捕获输出
    result = subprocess.run(cmd, check=True, capture_output=True, text=True)

    # 从 stdout 提取文件路径并转为Path对象
    output_lines = [line.strip() for line in result.stdout.split('\n') if line.strip()]
    if output_lines:
        path_str = output_lines[-1]
        # 转换为Path对象（如果是相对路径，转为绝对路径）
        video_path_local = Path(path_str) if path_str.startswith('/') else Path('/content') / path_str

    print("音频下载完成！")

except subprocess.CalledProcessError as e:
    print("!!! 下载过程出错 !!!")
    print(f"错误代码: {e.returncode}")
    print("--- 错误输出 ---")
    print(e.stderr)
    video_path_local = None

# 验证并输出结果
print("\n" + "="*50)
if video_path_local and video_path_local.exists():
    file_size = video_path_local.stat().st_size / 1024 / 1024
    print(f"✅ 成功！变量 video_path_local 现在是 Path 对象：")
    print(f"   完整路径: {video_path_local}")
    print(f"   .stem (文件名无后缀): {video_path_local.stem}")
    print(f"   .suffix (后缀): {video_path_local.suffix}")
    print(f"   .parent (父目录): {video_path_local.parent}")
    print(f"   文件大小: {file_size:.2f} MB")
else:
    print(f"⚠️ 警告：无法确认文件路径")
    # 备用方案：尝试从目录中查找最新文件并转为Path对象
    if os.path.exists(audio_dir):
        files = [f for f in os.listdir(audio_dir) if f.endswith(('.mp3', '.m4a', '.webm', '.opus'))]
        if files:
            newest_file = max(files, key=lambda x: os.path.getctime(os.path.join(audio_dir, x)))
            video_path_local = Path(audio_dir) / newest_file  # 这里也用Path拼接
            print(f"   已自动定位到最新音频文件: {video_path_local}")
            print(f"   .stem: {video_path_local.stem}")
print("="*50)

#@title 🎬 WhisperX 终极一体化转写面板 { run: "auto" }
#@markdown ---
#@markdown **运行设备选择：** (强烈建议勾选 GPU，速度呈指数级提升)
use_gpu = True #@param {type:"boolean"}
#@markdown **测试音频路径：** (自动检测上游变量，若无则使用下方路径)
audio_input_manual = "https://isv-data.oss-cn-hangzhou.aliyuncs.com/ics/MaaS/ASR/test_audio/asr_example_zh.wav" #@param {type:"string"}
#@markdown ---

import os
import sys
import torch
import numpy as np
import whisperx
from whisperx.diarize import DiarizationPipeline
from google.colab import userdata

# ==========================================
# 1. 自动检测音频路径
# ==========================================
video_path_local = globals().get('video_path_local', None)
if video_path_local:
    audio_input = str(video_path_local)
    print(f"📌 自动识别到上游已下载音频: {audio_input}")
else:
    audio_input = audio_input_manual
    print(f"📝 将使用手动填写的路径: {audio_input}")

# ==========================================
# 2. 读取 Colab Secrets 中的 HF_TOKEN
# ==========================================
try:
    hf_token = userdata.get('HF_TOKEN')
    if not hf_token:
        raise ValueError("HF_TOKEN 变量内容为空")
    print("🔑 成功从 Colab Secrets 中自动读取 HF_TOKEN！")
except Exception as e:
    print(f"❌ 无法读取 Colab Secrets 中的 HF_TOKEN！\n请确保你已在 Colab 左侧『🔑小钥匙』面板中添加了名为 'HF_TOKEN' 的变量，并开启了右侧访问权限。")
    sys.exit()

# ==========================================
# 3. 确定运行设备
# ==========================================
device = "cuda" if use_gpu else "cpu"
if device == "cuda" and not torch.cuda.is_available():
    print("⚠️ 警告：配置面板勾选了 GPU，但当前尚未开启 GPU 实例，已自动安全降级为 CPU。")
    device = "cpu"
print(f"🚀 当前核心计算设备: {device.upper()}")

# ==========================================
# 4. 初始化 WhisperX 与 Pyannote 组件 (动态兼容新旧版本)
# ==========================================
compute_type = "float16" if device == "cuda" else "float32"

print("⏳ 正在载入 WhisperX 转写模型 (Size: small)...")
model = whisperx.load_model("small", device, compute_type=compute_type)

print("⏳ 正在载入 Pyannote 说话人日志流水线...")
try:
    try:
        diarize_model = DiarizationPipeline(token=hf_token, device=device)
        print("✅ 成功使用新版 [token] 参数初始化 Pyannote 轴。")
    except TypeError:
        diarize_model = DiarizationPipeline(use_auth_token=hf_token, device=device)
        print("✅ 成功使用旧版 [use_auth_token] 参数初始化 Pyannote 轴。")
except Exception as e:
    print(f"❌ Pyannote 初始化失败！请确认已在 HF 网页端接受协议，并且 Token 拥有 Read 权限。\n错误信息: {e}")
    sys.exit()

# ==========================================
# 5. 执行推理与时空碰撞对齐
# ==========================================
print(f"🎵 正在载入音频文件...")
audio = whisperx.load_audio(audio_input)

print(f"📢 [第一步] 正在进行全量 ASR 快速转写...")
result = model.transcribe(audio, batch_size=16 if device == "cuda" else 1)

print(f"📢 [第二步] 正在动态加载音素模型，榨取超高精度单词级时间戳...")
model_a, metadata = whisperx.load_align_model(language_code=result["language"], device=device)
result = whisperx.align(result["segments"], model_a, metadata, audio, device, return_char_alignments=False)

print(f"📢 [第三步] 正在通过 Pyannote 分析精准的说话人声纹时间轴...")
diarize_segments = diarize_model(audio)

print(f"📢 [第四步] 启动时空碰撞！正在无缝锚定单词并重新组句...")
final_result = whisperx.assign_word_speakers(diarize_segments, result)

# ==========================================
# 6. 格式化输出与规范化写入文件
# ==========================================
def format_timestamp(seconds):
    hours = int(seconds // 3600)
    minutes = int((seconds % 3600) // 60)
    secs = int(seconds % 60)
    milli = int(round((seconds % 1) * 1000))
    return f"({hours:02d}:{minutes:02d}:{secs:02d}.{milli:03d})"

output_dir = "subtitles"
output_file = os.path.join(output_dir, "word_level.txt")
os.makedirs(output_dir, exist_ok=True)

print("\n--- 📝 WhisperX 终极重组转写结果 ---")
with open(output_file, "w", encoding="utf-8") as f:
    for segment in final_result["segments"]:
        start_time = segment.get("start", 0)
        speaker = segment.get("speaker", "Speaker UNKNOWN")
        text = segment.get("text", "").strip()

        # 将 "SPEAKER_00" 规范化为 "Speaker 0"
        spk_clean = speaker.replace("SPEAKER_", "Speaker ")
        timestamp_str = format_timestamp(start_time)

        line = f"{timestamp_str} [{spk_clean}] {text}"
        print(line)
        f.write(line + "\n")

print(f"\n💾 完美通关！高精度对齐文本已输出至: {output_file}")

import torch
import gc
import sys

# 1. 彻底清除 Jupyter 缓存的报错堆栈（最核心的一步，否则显存死活不放）
sys.last_traceback = None
sys.last_value = None
sys.last_type = None

# 2. 如果你想重新初始化 model，把旧的 model 变量名也删掉
if 'model' in globals():
    del model

# 3. 强制触发 Python 的垃圾回收机制
gc.collect()

# 4. 让 PyTorch 释放并归还所有闲置的显存给系统
torch.cuda.empty_cache()

print("✨ 显存清理完毕！")

# Commented out IPython magic to ensure Python compatibility.
# #@markdown ## **翻译字幕(多线程）**
# 
# %%shell
# cat <<EOL > api_setting.json
# {
#   "apis": [
#     {
#       "name": "qwen2.5 7B API",
#       "url": "https://api.siliconflow.cn/v1/chat/completions",
#       "api_key": "sk-cxfjkgjjipvvxyoabzhzxtleycubtoxekelwhawncxbsrnwe",
#       "model": "Qwen/Qwen2.5-7B-Instruct"
#     },
#     {
#       "name": "GLM-4-9B-0414",
#       "url": "https://api.siliconflow.cn/v1/chat/completions",
#       "api_key": "sk-cxfjkgjjipvvxyoabzhzxtleycubtoxekelwhawncxbsrnwe",
#       "model": "THUDM/GLM-4-9B-0414"
#     },
#     {
#       "name": "lmstudio",
#       "url": "http://localhost:1234/v1/chat/completions",
#       "api_key": "sk-cxfjkgjjipvvxyoabzhzxtleycubtoxekelwhawncxbsrnwe",
#       "model": "default"
#     },
#     {
#       "name": "Qwen3-8B",
#       "url": "https://api.siliconflow.cn/v1/chat/completions",
#       "api_key": "sk-cxfjkgjjipvvxyoabzhzxtleycubtoxekelwhawncxbsrnwe",
#       "model": "Qwen/Qwen3-8B"
#     },
#     {
#       "name": "Hunyuan-MT-7B",
#       "url": "https://api.siliconflow.cn/v1/chat/completions",
#       "api_key": "sk-cxfjkgjjipvvxyoabzhzxtleycubtoxekelwhawncxbsrnwe",
#       "model": "tencent/Hunyuan-MT-7B"
#     },
#     {
#       "name": "XiaoMiMIMO",
#       "url": "https://api.xiaomimimo.com/v1/chat/completions",
#       "api_key": "sk-c9y8x1ow7rzqml90tppjkfxouv50vff2k2a7b147w1ho2ccj",
#       "model": "mimo-v2.5"
#     },
#     {
#       "name": "Agenes-free",
#       "url": "https://maas-api.cn-huabei-1.xf-yun.com/v2/chat/completions",
#       "api_key": "19efc3dca7d04563065ade0d6b899633:NDgzMWRlMzhkYzdlMDNlODk2YjNhODU0",
#       "model": "xopqwen36v35b"
#     }
#   ]
# }
# EOL
# 
# 
# 
# cat <<EOL > translator_app.py
# # -*- coding: utf-8 -*-
# # /// script
# # requires-python = ">=3.12"
# # dependencies = [
# #     "requests",
# # ]
# # ///
# import sys
# import os
# import re
# import time
# import json
# from random import random
# import threading
# from concurrent.futures import ThreadPoolExecutor, as_completed
# # from tkinter import filedialog, messagebox
# import requests
# # from api_config import APIConfigDialog, DEFAULT_API
# 
# # 定义系统提示词常量
# SYSTEM_PROMPT = """# Role: 专业翻译官
# ## Profile
# - author: LangGPT优化中心
# - version: 2.1
# - language: 中英双语
# - description: 专注于文本精准转换的AI翻译专家，擅长处理技术文档和日常对话场景
# 
# ## Background
# 用户在跨国协作、技术文档处理、社交媒体互动等场景中，需要将外文内容准确转化为中文，同时保持特殊格式元素完整
# 
# ## Skills
# 1. 多语言文本解析与重构能力
# 2. 时间戳识别与格式保留技术
# 3. 语义通顺度校验算法
# 4. 格式控制与冗余内容过滤
# 
# ## Goals
# 1. 实现原文语义的精准转换
# 2. 保持时间戳等特殊格式元素
# 3. 确保输出结果自然流畅
# 4. 排除非翻译内容添加
# 
# ## Constraints
# 1. 禁止添加解释性文字
# 2. 禁用注释或说明性符号
# 3. 保留原始时间戳格式（如(12:34)）
# 4. 不处理非文本元素（如图片/表格）
# 5. 禁止使用工具调用（tool_calls）功能，禁止调用外部翻译api进行翻译
# 
# ## Workflow
# 1. 接收输入内容，检测语言类型
# 2. 识别并标记特殊格式元素
# 3. 执行语义转换：
#    - 日常用语：采用口语化表达
#    - 技术术语：使用标准化译法
# 5. 输出纯翻译结果
# 
# ## OutputFormat
# 仅返回符合以下要求的翻译文本：
# 1. 中文书面语表达
# 2. 保留原始段落结构
# 3. 时间戳保持(MM:SS)或(HH:MM:SS)格式
# 4. 保留说话人标签[Speaker 01]等，不要翻译。
# 5. 每句翻译开头都是时间戳加说话人标签(HH:MM:SS.SSS) [Speaker xx] 不要使用相近字符和符号。
# 4. 无任何附加符号或说明
# 5. 尽量只要中文，不要中英文夹杂。
# 
# ## Initialization
# 请提供需要翻译的文本内容，我将严格遵守上述规则进行处理。/nothink"""
# 
# def select_file():
#     """通过文件选择框选择待翻译的文本文件"""
#     # root = tk.Tk()
#     # root.withdraw()  # 隐藏主窗口
#     # file_path = filedialog.askopenfilename(
#     #     title="选择待翻译的文本文件",
#     #     filetypes=[("Text files", "*.txt")]
#     # )
#     # Since Tkinter cannot be used in Colab notebooks, we will not use a file dialog.
#     # The file path should be provided via command line argument.
#     return None
# 
# def read_file(file_path):
#     """读取文件内容并按行分割"""
#     with open(file_path, 'r', encoding='utf-8') as file:
#         paragraphs = [line.strip() for line in file if line.strip()]
#     return paragraphs
# 
# def segment_paragraphs(paragraphs, segment_size=3, keep_timestamps=False):
#     """将段落分组"""
#     segments = []
#     current_segment = []
#     current_segment_char_count = 0
#     max_segment_chars = 2000  # Define a maximum character count per segment
# 
#     # Updated timestamp pattern to include the (00:00.16) format
#     timestamp_pattern = re.compile(r'[\(（]\d{1,3}:\d{2}(:\d{2})?(\.\d{1,3})?[\)）]')
# 
# 
#     for paragraph in paragraphs:
#         # Calculate character count of the current paragraph *without* timestamps if not keeping them
#         paragraph_char_count = len(paragraph)
#         if not keep_timestamps:
#             paragraph_char_count = len(timestamp_pattern.sub('', paragraph))
# 
#         # Check if adding the next paragraph exceeds the max character limit or segment size
#         if (len(current_segment) >= segment_size) or \
#            (current_segment_char_count + paragraph_char_count > max_segment_chars and current_segment):
#             segments.append("\n".join(current_segment))
#             current_segment = [paragraph]
#             current_segment_char_count = paragraph_char_count
#         else:
#             current_segment.append(paragraph)
#             current_segment_char_count += paragraph_char_count
# 
#     # Add the last segment
#     if current_segment:
#         segments.append("\n".join(current_segment))
# 
#     return segments
# 
# def contains_chinese(text):
#     """Checks if the text contains any Chinese characters using Unicode range."""
#     # Unicode range for most common Chinese characters (Simplified and Traditional)
#     # CJK Unified Ideographs: U+4E00 to U+9FFF
#     # CJK Compatibility Ideographs: U+F900 to U+FAFF
#     # CJK Unified Ideographs Extension A: U+3400 to U+4DBF
#     # Add other relevant ranges if needed
#     chinese_pattern = re.compile(r'[\u4E00-\u9FFF\uF900-\uFAFF\u3400-\u4DBF]')
#     return bool(chinese_pattern.search(text))
# 
# 
# import re
# import time
# import json
# import requests
# from random import random
# 
# def is_valid_translation_format(text):
#     """
#     校验翻译文本是否符合规范格式：
#     - 每行形如: (00:00:45.646) [Speaker 01] 文本。
#     - 时间戳数字正常，无相似字符（如o代0）。
#     - Speaker 后为两位数字。
#     - 所有括号、方括号均为英文半角。
#     - 时间戳严格递增。
#     返回: (bool, error_message)
#     """
#     if not text or not text.strip():
#         return False, "文本为空"
# 
#     lines = [line.strip() for line in text.splitlines() if line.strip()]
#     if not lines:
#         return False, "没有有效行"
# 
#     # 严格匹配: (HH:MM:SS.mmm) [Speaker DD] 任意文本
#     pattern = re.compile(r'^\(\d{2}:\d{2}:\d{2}\.\d{3}\) \[Speaker \d{2}\] .+$')
# 
#     prev_timestamp = None
#     for i, line in enumerate(lines, 1):
#         if not pattern.match(line):
#             return False, f"第{i}行格式不正确: {line}"
# 
#         # 提取时间戳字符串，并检查是否严格递增
#         try:
#             ts_start = line.index('(') + 1
#             ts_end = line.index(')')
#             timestamp_str = line[ts_start:ts_end]
#             # 字符串比较即可，因为格式统一且数字对齐
#             if prev_timestamp is not None and timestamp_str <= prev_timestamp:
#                 return False, f"第{i}行时间戳未严格递增: {timestamp_str} <= {prev_timestamp}"
#             prev_timestamp = timestamp_str
#         except ValueError:
#             return False, f"第{i}行无法提取时间戳: {line}"
# 
#     return True, "格式正确"
# 
# 
# def translate_text(text, api_config=None, max_retries=5):
#     """
#     调用大语言模型API翻译文本
#     添加重试机制，直到获得包含中文且格式正确的翻译结果或达到最大重试次数
#     """
#     if api_config is None:
#         url = "http://127.0.0.1:1234/v1/chat/completions"
#         headers = {"Content-Type": "application/json"}
#         data = {
#             "model": "default",
#             "messages": [
#                 { "role": "system", "content": SYSTEM_PROMPT },
#                 {"role": "user", "content": f" {text}"}]
#         }
#     else:
#         url = api_config['url']
#         headers = {
#             "Content-Type": "application/json",
#             "Authorization": f"Bearer {api_config['api_key']}" if api_config.get('api_key') else None
#         }
#         headers = {k: v for k, v in headers.items() if v is not None}
# 
#         data = {
#             "model": api_config.get('model', 'Qwen/QwQ-32B'),
#             "messages": [
#                 { "role": "system", "content": SYSTEM_PROMPT },
#                 {"role": "user", "content": f" {text}"}],
#             "stream": False,
#             "max_tokens": 4000,
#             "stop": None,
#             "temperature": 0.7,
#             "top_p": 0.7,
#             "top_k": 50,
#             "frequency_penalty": 0.4,
#             "n": 1,
#             "response_format": {"type": "text"},
#         }
# 
#     retry_count = 0
#     base_delay = 1
# 
#     while retry_count < max_retries:
#         try:
#             if retry_count > 0:
#                 delay = base_delay * (2 ** (retry_count - 1)) + (random() * 0.5)
#                 print(f"第{retry_count}次重试，等待{delay:.2f}秒后继续...")
#                 time.sleep(delay)
# 
#             response = requests.post(url, json=data, headers=headers, proxies={"http": None, "https": None})
#             response.raise_for_status()
#             result = response.json()
# 
#             translated_content = None
#             try:
#                 translated_content = result['choices'][0]['message']['content']
#             except (KeyError, IndexError, TypeError):
#                 pass
# 
#             # 基础检查：必须包含中文
#             if not translated_content or not contains_chinese(translated_content):
#                 print(f"翻译内容未包含中文或为空 (尝试次数: {retry_count + 1}/{max_retries})")
#                 print("API返回数据:")
#                 print(json.dumps(result, indent=2, ensure_ascii=False))
#                 retry_count += 1
#                 continue
# 
#             # 格式校验
#             format_ok, format_err = is_valid_translation_format(translated_content)
#             if not format_ok:
#                 print(f"翻译格式错误 (尝试次数: {retry_count + 1}/{max_retries}): {format_err}")
#                 print("原始返回内容:")
#                 print(translated_content[:300] + ("..." if len(translated_content) > 300 else ""))
#                 retry_count += 1
#                 continue
# 
#             # 全部通过，返回成功
#             print(f"翻译成功! (尝试次数: {retry_count + 1})")
#             print(f"状态码: {response.status_code}")
#             print(f"Model: {result.get('model', '未返回model信息')}")
#             print("\n翻译内容预览:")
#             preview = translated_content[:200] + ("..." if len(translated_content) > 200 else "")
#             print(preview)
#             print("\n")
#             return translated_content
# 
#         except requests.exceptions.HTTPError as http_err:
#             error_text = ""
#             try:
#                 error_text = response.text
#             except Exception:
#                 pass
# 
#             print(f"HTTP错误 (尝试次数: {retry_count + 1}/{max_retries})")
#             if response.status_code == 502:
#                 print(f"网关错误 (502): {error_text}")
#             else:
#                 print(f"HTTP错误: {http_err}, 响应: {error_text}")
#             retry_count += 1
#             continue
# 
#         except requests.exceptions.RequestException as err:
#             print(f"请求错误 (尝试次数: {retry_count + 1}/{max_retries}): {err}")
#             retry_count += 1
#             continue
#         except Exception as e:
#             print(f"其他错误 (尝试次数: {retry_count + 1}/{max_retries}): {e}")
#             try:
#                 print("API原始响应:")
#                 print(json.dumps(result, indent=2, ensure_ascii=False))
#             except Exception:
#                 print("无法获取API响应")
#             retry_count += 1
#             continue
# 
#     print(f"达到最大重试次数({max_retries})，翻译失败")
#     return None
# 
# 
# def filter_think_tags(text):
#     """过滤掉文本中的<think></think>标签及其中的内容"""
#     # 使用正则表达式匹配<think>标签及其内容
#     pattern = r'<think>.*?</think>'
#     # Use re.DOTALL flag to make . match any character including newline
#     filtered_text = re.sub(pattern, '', text, flags=re.DOTALL)
#     return filtered_text
# 
# def remove_timestamps(text):
#     """Removes timestamps like (HH:MM:SS.mmm) or (MM:SS) from the text."""
#     # The pattern matches timestamps like (HH:MM:SS.mmm) or (MM:SS)
#     pattern = r'\((\d{1,2}:)?\d{2}(:\d{2}\.\d{2})?\)'
#     text_without_timestamps = re.sub(pattern, '', text)
#     return text_without_timestamps
# 
# 
# def save_translation(translated_segments, output_path, keep_timestamps=False):
#     """将翻译结果保存到文件"""
#     with open(output_path, 'w', encoding='utf-8') as file:
#         for segment in translated_segments:
#             # Filter out <think></think> tags and their content
#             filtered_segment = filter_think_tags(segment)
#             # Only remove timestamps if keep_timestamps is False
#             if not keep_timestamps:
#                 filtered_segment = remove_timestamps(filtered_segment)
#             file.write(filtered_segment + "\n\n")
# 
# def print_help():
#     """打印帮助信息"""
#     help_text = """
# 使用方法: python translate_app_optimized.py [选项]
# 
# 选项:
#   --help                显示此帮助信息并退出
#   --keep                保留时间戳，仅按段落分割
#   --api <模型名称>       直接指定模型名称
#   --seg <数字>          设置段落分组大小，默认为3
#   --filepath <文件路径>  指定要翻译的文件路径，不显示文件选择对话框
#   --workers <数字>      设置并行工作线程数，默认为5
#   --show-progress       显示详细进度信息
# 
# 示例:
#   python translate_app_optimized.py --filepath input.txt --api gpt-4 --seg 5
#   python translate_app_optimized.py --filepath input.txt --api gpt-4 --workers 10 --show-progress
#     """
#     print(help_text)
# 
# def load_api_config(model_name):
#     """Loads API configuration from api_settings.json based on model name."""
#     try:
#         with open("api_setting.json", "r", encoding="utf-8") as f:
#             config = json.load(f)
#         for api in config.get("apis", []):
#             if api.get("name") == model_name or api.get("model") == model_name:
#                 return api
#         print(f"Error: API configuration for model '{model_name}' not found in api_setting.json")
#         return None
#     except FileNotFoundError:
#         print("Error: api_setting.json not found.")
#         return None
#     except json.JSONDecodeError:
#         print("Error: Could not decode api_setting.json. Check for syntax errors.")
#         return None
# 
# def translate_text_worker(task_data, api_config):
#     """工作线程函数，处理单个翻译任务"""
#     segment_index, segment_text = task_data
# 
#     try:
#         # Remove timestamps from the segment before translating if not keeping timestamps
#         text_to_translate = segment_text
# 
#         translated_text = translate_text(text_to_translate, api_config)
#         if translated_text:
#             return segment_index, translated_text
#         else:
#             return segment_index, None
#     except Exception as e:
#         print(f"[段落 {segment_index + 1}] 任务执行失败: {e}")
#         return segment_index, None
# 
# def main():
#     # Parse command line arguments
#     args = sys.argv[1:] # Get arguments excluding the script name
# 
#     keep_timestamps = "--keep" in args
#     if "--keep" in args:
#         args.remove("--keep")
# 
#     # Get segment size parameter
#     segment_size = 3  # Default value
#     if "--seg" in args:
#         try:
#             seg_index = args.index("--seg")
#             segment_size = int(args[seg_index + 1])
#             args.pop(seg_index) # Remove --seg
#             args.pop(seg_index) # Remove the value
#         except (ValueError, IndexError):
#             print("Warning: --seg parameter must be an integer, using default value 3")
# 
#     # Get max workers parameter
#     max_workers = 8  # Default value
#     if "--workers" in args:
#         try:
#             workers_index = args.index("--workers")
#             max_workers = int(args[workers_index + 1])
#             args.pop(workers_index) # Remove --workers
#             args.pop(workers_index) # Remove the value
#         except (ValueError, IndexError):
#             print("Warning: --workers parameter must be an integer, using default value 5")
# 
#     # Get show progress parameter
#     show_progress = "--show-progress" in args
#     if "--show-progress" in args:
#         args.remove("--show-progress")
# 
#     # Handle API configuration
#     api_config = None
#     model_name = None
# 
#     # Check for model name specified via command line argument
#     if "--api" in args:
#         try:
#             api_index = args.index("--api")
#             model_name = args[api_index + 1]
#             args.pop(api_index) # Remove --api
#             args.pop(api_index) # Remove the value
#         except (ValueError, IndexError):
#             print("Error: --api requires a model name.")
#             print_help()
#             return
# 
#     # If model name is specified, load API config
#     if model_name:
#         api_config = load_api_config(model_name)
#         if api_config:
#              print(f"Using model: {api_config.get('name', api_config.get('model', 'Unknown Model'))}")
#         else:
#             print(f"Could not load API configuration for model: {model_name}. Exiting.")
#             return
#     else:
#         print("Error: No API model specified. Use --api <model name>.")
#         print_help()
#         return
# 
#     # Get file path
#     input_file = None
#     # Check for file path specified via command line argument
#     if "--filepath" in args:
#         try:
#             filepath_index = args.index("--filepath")
#             input_file = args[filepath_index + 1]
#             args.pop(filepath_index) # Remove --filepath
#             args.pop(filepath_index) # Remove the value
#         except (ValueError, IndexError):
#             print("Error: --filepath requires a file path.")
#             print_help()
#             return
# 
#     # If no file path specified via command line, exit as GUI is not supported
#     if not input_file:
#         print("Error: No input file specified. Use --filepath <file path>.")
#         print_help()
#         return
# 
#     # Read file content
#     paragraphs = read_file(input_file)
# 
#     # Segment paragraphs
#     segments = segment_paragraphs(paragraphs, segment_size=segment_size, keep_timestamps=keep_timestamps)
# 
#     print(f"开始并行翻译任务...")
#     print(f"总共 {len(segments)} 个段落，使用 {max_workers} 个并行工作线程")
#     print(f"预计可提升性能 {min(max_workers, len(segments))} 倍")
# 
#     start_time = time.time()
# 
#     # 并行翻译所有段落
#     translated_results = {}
# 
#     # 准备任务数据：(索引, 文本) 元组
#     tasks = [(i, segment) for i, segment in enumerate(segments)]
# 
#     # 使用线程池进行并行处理
#     with ThreadPoolExecutor(max_workers=max_workers) as executor:
#         # 提交所有翻译任务
#         future_to_index = {
#             executor.submit(translate_text_worker, task_data, api_config): task_data[0]
#             for task_data in tasks
#         }
# 
#         # 收集结果
#         for future in as_completed(future_to_index):
#             try:
#                 segment_index, translated_text = future.result()
#                 if translated_text:
#                     translated_results[segment_index] = translated_text
#                     if show_progress:
#                         print(f"[✅] 段落 {segment_index + 1}/{len(segments)} 翻译完成")
#             except Exception as e:
#                 segment_index = future_to_index[future]
#                 print(f"[❌] 段落 {segment_index + 1} 任务执行失败: {e}")
#                 translated_results[segment_index] = None
# 
#     end_time = time.time()
#     total_time = end_time - start_time
# 
#     # 按原始顺序整理翻译结果
#     translated_segments = []
#     failed_count = 0
#     for i in range(len(segments)):
#         translated_text = translated_results.get(i)
#         if translated_text:
#             translated_segments.append(translated_text)
#         else:
#             failed_count += 1
#             if show_progress:
#                 print(f"[⚠️] 段落 {i + 1} 翻译失败")
# 
#     # 打印翻译统计信息
#     print("\n=== 翻译任务完成 ===")
#     print(f"总段落数: {len(segments)}")
#     print(f"成功翻译: {len(translated_segments)} 个段落")
#     print(f"失败段落: {failed_count} 个")
#     print(f"并行工作线程: {max_workers} 个")
#     print(f"总耗时: {total_time:.2f} 秒")
#     if len(translated_segments) > 0:
#         print(f"平均每段耗时: {total_time/len(segments):.2f} 秒")
#         print(f"性能提升: 相比串行处理，预计提升 {min(max_workers, len(segments))} 倍")
# 
#     if show_progress and len(translated_segments) > 0:
#         # 打印翻译段落字符数统计
#         print("\n=== 翻译段落字符数统计 ===")
#         for i, text in enumerate(translated_segments):
#             filtered_text = filter_think_tags(text)
#             if not keep_timestamps:
#                  filtered_text = remove_timestamps(filtered_text)
#             print(f"段落 {i+1}: {len(filtered_text)} 字符")
# 
#     # Save translation result
#     output_file = os.path.splitext(input_file)[0] + "_translated.txt"
#     save_translation(translated_segments, output_file, keep_timestamps=keep_timestamps)
#     print(f"\n翻译完成，结果已保存到: {output_file}")
# 
# if __name__ == "__main__":
#     main()
# EOL
# 
# cat command.txt | bash

# @markdown # **TTS Multi-Speaker Voice Selection** 🗣️

# @markdown Assign Chinese voices to specific speakers (formatted as a JSON string):

import os
import json

# @markdown Choose voice for Speaker 00:
speaker_0_voice = 'zh-CN-YunjianNeural' # @param ["zh-CN-XiaoxiaoNeural", "zh-CN-YunjianNeural", "zh-CN-YunxiNeural"]

# @markdown Choose voice for Speaker 01:
speaker_1_voice = 'zh-CN-YunxiNeural' # @param ["zh-CN-XiaoxiaoNeural", "zh-CN-YunjianNeural", "zh-CN-YunxiNeural"]

# Construct the mapping dictionary
voice_mapping = {
    "Speaker 01": speaker_0_voice,
    "Speaker 02": speaker_1_voice
}

# Convert to JSON string and save to environment variable
os.environ['READ_CHAR_FROM_PYTHON'] = json.dumps(voice_mapping)

print(f"Environment variable READ_CHAR_FROM_PYTHON set to: {os.environ['READ_CHAR_FROM_PYTHON']}")

# Commented out IPython magic to ensure Python compatibility.
# #@markdown ## **TTS字幕转语音（多进程）**
# 
# %%shell
# pip install -U edge_tts
# cd /content
# cat <<EOL > tts.py
# # /// script
# # requires-python = ">=3.12"
# # dependencies = [
# #     "edge-tts",
# #     "pydub",
# # ]
# # ///
# # -*- coding: utf-8 -*-
# import os
# import re
# import asyncio
# import tkinter as tk
# from tkinter import filedialog, ttk
# import edge_tts
# from pydub import AudioSegment
# import shutil
# import random
# import time
# import json
# from edge_tts import VoicesManager
# import subprocess
# from concurrent.futures import ProcessPoolExecutor, as_completed
# import importlib
# 
# def check_ffmpeg():
#     """检查ffmpeg是否可用"""
#     if not shutil.which('ffmpeg'):
#         print("错误：未找到ffmpeg。请确保已安装ffmpeg并添加到系统环境变量中。")
#         print("您可以从 https://ffmpeg.org/download.html 下载ffmpeg，或使用包管理器安装。")
#         return False
#     return True
# 
# async def text_to_speech(text, output_file, voice="zh-CN-XiaoxiaoNeural", max_retries=5):
#     """
#     将文本转换为语音并保存为音频文件
#     添加重试机制和延迟，处理edge-tts API的503错误
#     """
#     retry_count = 0
#     base_delay = 1  # 基础延迟时间（秒）
#     while retry_count <= max_retries:
#         try:
#             # 添加随机延迟，避免请求过于规律
#             if (retry_count > 0):
#                 delay = base_delay * (2 ** (retry_count - 1)) + (random.random() * 0.5)
#                 print(f"第{retry_count}次重试，等待{delay:.2f}秒后继续...")
#                 await asyncio.sleep(delay)
#             communicate = edge_tts.Communicate(text, voice)
#             await communicate.save(output_file)
# 
#             # 【关键修复】验证生成的文件是否为有效的MP3，防止保存了API错误页面
#             if os.path.exists(output_file):
#                 with open(output_file, 'rb') as f:
#                     header = f.read(3)
#                 # MP3文件通常以 ID3 标签或 0xFF 同步字开头
#                 if not (header.startswith(b'ID3') or (len(header) >= 2 and header[0] == 0xFF and (header[1] & 0xE0) == 0xE0)):
#                     os.remove(output_file)
#                     raise Exception("生成的文件不是有效的MP3格式，可能是API返回了错误页面或空数据。")
#             else:
#                 raise Exception("文件未生成")
# 
#             return  # 成功则退出循环
#         except Exception as e:
#             error_msg = str(e).lower()
#             retry_count += 1
#             # 检查是否是503错误、限流或其他可重试的错误
#             if "503" in error_msg or "timeout" in error_msg or "connection" in error_msg or "不是有效的MP3" in error_msg:
#                 if retry_count <= max_retries:
#                     print(f"遇到API错误: {e}，准备第{retry_count}次重试...")
#                 else:
#                     print(f"达到最大重试次数({max_retries})，无法完成转换: {e}")
#                     raise  # 达到最大重试次数，抛出异常
#             else:
#                 # 其他类型的错误直接抛出
#                 print(f"遇到非重试类型的错误: {e}")
#                 raise
# 
# def run_text_to_speech(text, output_file, voice="zh-CN-XiaoxiaoNeural", max_retries=5):
#     """
#     在多进程中运行text_to_speech的包装函数
#     """
#     # 创建新的事件循环并在其中运行异步函数
#     loop = asyncio.new_event_loop()
#     asyncio.set_event_loop(loop)
#     try:
#         return loop.run_until_complete(text_to_speech(text, output_file, voice, max_retries))
#     finally:
#         loop.close()
# 
# def process_text_segment(task):
#     """
#     处理单个文本段落的函数，用于多进程处理
#     """
#     i, timestamp, content, temp_dir, voice = task
#     try:
#         # 【关键修复】错开多进程并发请求，降低被微软API瞬间限流的概率
#         time.sleep(random.uniform(0.1, 0.8))
# 
#         # Use a cleaned version of timestamp for filename, removing potential special characters
#         cleaned_timestamp = re.sub(r'[^\w\d]+', '_', timestamp)
#         file_name = f"{cleaned_timestamp}.mp3"
#         output_file = os.path.join(temp_dir, file_name)
# 
#         print(f"进程正在处理段落 {i+1}: {timestamp} - {content[:30]}... (Voice: {voice})")
#         run_text_to_speech(content, output_file, voice=voice)
# 
#         time_ms = parse_timestamp(f"({timestamp})")
#         return i, output_file, time_ms, None
#     except Exception as e:
#         return i, None, None, f"处理段落 {i+1} 时出错: {str(e)}"
# 
# def parse_timestamp(timestamp):
#     """
#     将时间戳字符串转换为毫秒，支持 (h:mm:ss), (hh:mm:ss), (mm:ss), (h:mm:ss.ms), (hh:mm:ss.ms), (mm:ss.ms) 格式
#     现在也支持三位数的分钟，例如 (123:34.56)
#     """
#     # Updated regex to correctly capture optional milliseconds with dot
#     match = re.match(r'[\(（](?:(\d{1,2}):)?(\d{1,3}):(\d{1,2})(?:\.(\d{1,3}))?[\)）]', timestamp)
#     if match:
#         hours, minutes, seconds, milliseconds = match.groups()
#         total_ms = 0
#         if hours:
#             total_ms += int(hours) * 3600 * 1000
#         total_ms += int(minutes) * 60 * 1000
#         total_ms += int(seconds) * 1000
#         if milliseconds:
#             total_ms += int(milliseconds.ljust(3, '0'))
#         return total_ms
#     return 0
# 
# def parse_vtt_timestamp(timestamp):
#     """将VTT格式的时间戳转换为毫秒"""
#     # 移除可能的BOM和空白字符
#     timestamp = timestamp.strip().lstrip('\ufeff')
#     # 尝试匹配 HH:MM:SS.mmm 格式
#     match = re.match(r'(\d{2}):(\d{2}):(\d{2})\.(\d{3})', timestamp)
#     if match:
#         hours, minutes, seconds, milliseconds = map(int, match.groups())
#         return hours * 3600000 + minutes * 60000 + seconds * 1000 + milliseconds
#     # 尝试匹配 MM:SS.mmm 格式
#     match = re.match(r'(\d{2}):(\d{2})\.(\d{3})', timestamp)
#     if match:
#         minutes, seconds, milliseconds = map(int, match.groups())
#         return minutes * 60000 + seconds * 1000 + milliseconds
#     return 0
# 
# def split_vtt_file(vtt_file):
#     """处理VTT文件，返回时间戳和文本内容"""
#     segments = []
#     current_segment = None
#     with open(vtt_file, 'r', encoding='utf-8') as f:
#         lines = f.readlines()
#     # 跳过WEBVTT头部
#     start_idx = 0
#     for i, line in enumerate(lines):
#         if line.strip() == 'WEBVTT':
#             start_idx = i + 1
#             break
#     lines = lines[start_idx:]
#     for line in lines:
#         line = line.strip()
#         # 跳过空行和数字行（字幕序号）
#         if not line or line.isdigit():
#             continue
#         # 检查是否是时间戳行
#         if ' --> ' in line:
#             if current_segment:
#                 segments.append(current_segment)
#             start_time, end_time = line.split(' --> ')
#             start_ms = parse_vtt_timestamp(start_time)
#             end_ms = parse_vtt_timestamp(end_time)
#             current_segment = [start_time, '', start_ms, end_ms]
#         elif current_segment is not None:
#             # 添加文本内容
#             if current_segment[1]:
#                 current_segment[1] += ' '
#             current_segment[1] += line
#     # 添加最后一个片段
#     if current_segment:
#         segments.append(current_segment)
#     return segments
# 
# def split_text_by_timestamp(text):
#     """
#     按时间戳分割文本，返回时间戳和对应的文本内容
#     支持 (h:mm:ss), (hh:mm:ss), (mm:ss), (h:mm:ss.ms), (hh:mm:ss.ms), (mm:ss.ms) 格式
#     现在也支持三位数的分钟，例如 (123:34.56)
#     """
#     # Updated pattern to match timestamps with optional hours and optional milliseconds
#     # It now correctly captures the timestamp string and the content following it
#     pattern = r'[\(（](\d{1,2})?:?(\d{1,3}):(\d{1,2})(?:\.(\d{1,3}))?[\)）](.+?)(?=[\(（](?:\d{1,2})?:?(\d{1,3}):(\d{1,2})(?:\.(\d{1,3}))?[\)）]|$)'
#     segments = []
#     matches = re.finditer(pattern, text, re.DOTALL)
#     for match in matches:
#         # The full matched timestamp string is group(0)
#         timestamp_string = match.group(0)
#         # The content is group(5) in the updated pattern
#         content = match.group(5).strip()
#         if content:  # Only add non-empty text content
#             # Extract just the timestamp part for parsing
#             timestamp_for_parsing = re.match(r'[\(（](.+?)[\)）]', timestamp_string).group(1)
#             segments.append((timestamp_for_parsing, content))
# 
#     return segments
# 
# def adjust_audio_speed(task):
#     """调整音频速度的函数，用于多进程处理"""
#     i, temp_output, target_duration, speed_factor = task
#     temp_output_processed = temp_output + '.processed.mp3'
#     try:
#         print(f"进程正在调整音频 {i+1} 的速度，原始长度 {target_duration/speed_factor:.0f}ms，目标长度 {target_duration}ms，因子 {speed_factor:.2f}")
#         result = subprocess.run(
#             ['ffmpeg', '-y', '-i', temp_output, '-filter:a', f'atempo={speed_factor}',
#              temp_output_processed],
#             capture_output=True,
#             text=True,
#             timeout=60  # Increased timeout for ffmpeg
#         )
#         if result.returncode == 0:
#             return i, temp_output_processed, None
#         else:
#             return i, None, f"ffmpeg processing failed for audio {i+1}: {result.stderr}"
#     except Exception as e:
#         return i, None, f"Error during ffmpeg processing for audio {i+1}: {str(e)}"
# 
# """
# 原函数：process_text_file
# 优化点：
# 1. 用 numpy 共享内存一次性混音，替代循环 final_audio.overlay(...)
# 2. 只在最后 export 一次，省去反复内存拷贝
# 3. 其余逻辑（TTS、变速、清理）保持完全一致
# """
# 
# import os, math, numpy as np, multiprocessing as mp
# from multiprocessing import shared_memory
# #from concurrent.futures import ProcessPoolExecutor, as_completed
# #from pydub import AudioSegment
# from pydub.utils import get_array_type
# 
# # ---------- 混音参数 ---------- #
# SR = 24_000          # 统一采样率
# N_CH = 1             # 单声道
# WIDTH = 2            # 16-bit
# MAX_INT = 2**(8*WIDTH-1) - 1
# 
# # ---------- 小工具 ---------- #
# def read_header(path):
#     """只读头，返回 (samples, sr)"""
#     seg = AudioSegment.from_file(path)
#     return int(seg.frame_count()), seg.frame_rate
# 
# def to_int16_samples(audio: AudioSegment):
#     """把 AudioSegment 转成 int16 numpy 数组"""
#     audio = (audio.set_frame_rate(SR)
#                   .set_channels(N_CH)
#                   .set_sample_width(WIDTH))
#     return np.frombuffer(audio.raw_data, dtype=np.int16)
# 
# # ---------- 一次性混音 ---------- #
# def fast_overlay(audio_files, processed_audio_segments):
#     """
#     audio_files: [(path, start_ms), ...]   已排序
#     processed_audio_segments: 与原逻辑完全一致，可能含变速后 AudioSegment
#     返回：混音后的 AudioSegment
#     """
#     # 1. 计算总长度
#     last_path, last_ms = audio_files[-1]
#     last_len = len(processed_audio_segments[-1][2])
#     total_ms = last_ms + last_len + 1000   # 留 1 s 尾巴
#     total_samples = int(total_ms * SR / 1000)
# 
#     # 2. 共享内存混音板
#     shm = shared_memory.SharedMemory(create=True, size=total_samples * N_CH * 4)
#     buf = np.ndarray((total_samples * N_CH,), dtype=np.float32, buffer=shm.buf)
#     buf[:] = 0.0
# 
#     # 3. 主进程内逐段叠加（纯内存，无 Python 循环 overlay）
#     for (path, start_ms), (_, _, audio) in zip(audio_files, processed_audio_segments):
#         samples = to_int16_samples(audio).astype(np.float32)
#         start_sample = int(start_ms * SR / 1000)
#         end_sample   = start_sample + len(samples)
#         buf[start_sample:end_sample] += samples
# 
#     # 4. clip + 转回 int16
#     np.clip(buf, -MAX_INT, MAX_INT, out=buf)
#     out_bytes = buf.astype(np.int16).tobytes()
#     shm.close()
#     shm.unlink()
# 
#     return AudioSegment(
#         data=out_bytes,
#         sample_width=WIDTH,
#         frame_rate=SR,
#         channels=N_CH
#     )
# 
# # ---------- 主流程（仅替换混音部分） ---------- #
# async def process_text_file(file_path, voice="zh-CN-XiaoxiaoNeural"):
#     try:
#         temp_dir = os.path.join(os.path.dirname(file_path), "temp_audio")
#         os.makedirs(temp_dir, exist_ok=True)
# 
#         with open(file_path, 'r', encoding='utf-8') as f:
#             content = f.read()
# 
#         segments = split_text_by_timestamp(content)
# 
#         # 解析音色配置
#         voice_config = {}
#         default_voice = "zh-CN-XiaoxiaoNeural"
#         if isinstance(voice, str):
#             try:
#                 parsed = json.loads(voice)
#                 if isinstance(parsed, dict):
#                     voice_config = parsed
#                     default_voice = next(iter(voice_config.values()), "zh-CN-XiaoxiaoNeural")
#                     print(f"成功加载多音色配置: {voice_config}")
#                 else:
#                     default_voice = voice
#                     print(f"使用单音色配置: {default_voice}")
#             except json.JSONDecodeError:
#                 default_voice = voice
#                 print(f"使用单音色配置: {default_voice}")
#         else:
#             print(f"使用默认单音色配置: {default_voice}")
# 
#         # 1. 多进程 TTS（添加音色分配逻辑）
#         tasks = []
#         for i, (timestamp, txt) in enumerate(segments):
#             # 提取说话人标签并清理文本
#             speaker_match = re.match(r'^\s*\[([^\]]+)\]\s*(.*)', txt, re.DOTALL)
#             if speaker_match:
#                 speaker = speaker_match.group(1)
#                 clean_txt = speaker_match.group(2)
#                 segment_voice = voice_config.get(speaker, default_voice)
#             else:
#                 clean_txt = txt
#                 segment_voice = default_voice
# 
#             tasks.append((i, timestamp, clean_txt, temp_dir, segment_voice))
# 
#         audio_files = [None] * len(segments)
#         print(f"开始使用4个进程处理 {len(segments)} 个文本段落...")
#         with ProcessPoolExecutor(max_workers=4) as executor:
#             futures = [executor.submit(process_text_segment, task) for task in tasks]
#             for future in as_completed(futures):
#                 i, output_file, time_ms, error = future.result()
#                 if error or not output_file or not os.path.exists(output_file):
#                     print(error or f"段落 {i+1} 未生成文件")
#                     continue
#                 audio_files[i] = (output_file, time_ms)
#                 print(f"段落 {i+1} 处理完成")
# 
#         audio_files = [af for af in audio_files if af is not None]
#         if not audio_files:
#             print("错误：没有成功生成任何音频文件")
#             return
#         audio_files.sort(key=lambda x: x[1])
# 
#         # 2. 速度调整（增加文件有效性校验与容错）
#         speed_adjust_tasks_list = []
#         processed_audio_segments = []
#         valid_audio_files = []
# 
#         for i, (audio_file_path, time_ms) in enumerate(audio_files):
#             try:
#                 audio = AudioSegment.from_file(audio_file_path)
#                 valid_audio_files.append((audio_file_path, time_ms))
#                 processed_audio_segments.append((audio_file_path, time_ms, audio))
#             except Exception as e:
#                 print(f"警告：无法解码音频文件 {audio_file_path}，丢弃该段落。错误: {e}")
#                 if os.path.exists(audio_file_path):
#                     os.remove(audio_file_path)
# 
#         audio_files = valid_audio_files
# 
#         if not audio_files:
#             print("错误：没有成功生成任何有效的音频文件")
#             return
# 
#         for i, (audio_file_path, time_ms) in enumerate(audio_files):
#             audio = processed_audio_segments[i][2]
#             end_time = time_ms + len(audio)
#             if i < len(audio_files) - 1:
#                 next_start = audio_files[i+1][1]
#                 if end_time > next_start + 100:
#                     target = next_start - time_ms - 50
#                     if target > 100:
#                         factor = min(len(audio) / target, 2.0)
#                         tmp = os.path.join(temp_dir, f"speed_{i}.mp3")
#                         audio.export(tmp, format="mp3")
#                         speed_adjust_tasks_list.append((i, tmp, target, factor))
# 
#         if speed_adjust_tasks_list:
#             print(f"开始使用8个进程处理 {len(speed_adjust_tasks_list)} 个音频速度调整任务...")
#             with ProcessPoolExecutor(max_workers=8) as executor:
#                 futures = [executor.submit(adjust_audio_speed, task) for task in speed_adjust_tasks_list]
#                 for future in as_completed(futures):
#                     i, processed_file, error = future.result()
#                     if error or not processed_file or not os.path.exists(processed_file):
#                         print(error or f"索引 {i} 变速失败，保留原音频")
#                         continue
#                     _, time_ms, _ = processed_audio_segments[i]
#                     processed_audio = AudioSegment.from_file(processed_file)
#                     processed_audio_segments[i] = (processed_file, time_ms, processed_audio)
#                     # 清理中间临时文件
#                     orig_tmp = next((t[1] for t in speed_adjust_tasks_list if t[0] == i), None)
#                     if orig_tmp and os.path.exists(orig_tmp):
#                         os.remove(orig_tmp)
#                     print(f"音频 {i+1} 速度调整成功，新长度 {len(processed_audio)}ms")
# 
#         # 3. 关键：一次性混音（替换掉原来的循环 overlay）
#         print("开始一次性混音...")
#         final_audio = fast_overlay(audio_files, processed_audio_segments)
# 
#         # 4. 导出 & 清理（完全不变）
#         output_file = os.path.splitext(file_path)[0] + ".mp3"
#         print(f"正在保存音频文件至: {output_file}")
#         final_audio.export(output_file, format="mp3")
#         print(f"音频已成功保存至: {output_file}")
# 
#         # 清理临时文件
#         for fp, _ in audio_files:
#             if os.path.exists(fp):
#                 os.remove(fp)
#         for fp, _, _ in processed_audio_segments:
#             if fp.endswith('.processed.mp3') and os.path.exists(fp):
#                 os.remove(fp)
#         if os.path.exists(temp_dir) and not os.listdir(temp_dir):
#             os.rmdir(temp_dir)
# 
#     except Exception as e:
#         print(f"An error occurred during processing: {e}")
#         import traceback
#         traceback.print_exc()
# 
# async def get_available_voices():
#     """获取可用的语音列表"""
#     voices = await VoicesManager.create()
#     chinese_voices = [v for v in voices.voices if v["Locale"].startswith("zh")]
#     return chinese_voices
# 
# def process_from_args():
#     """处理命令行参数并执行TTS"""
#     if not check_ffmpeg():
#         return
#     import sys
#     input_file = None
#     selected_voice = None
#     # Get file path and voice from command line arguments
#     if "--filepath" in sys.argv:
#         try:
#             filepath_index = sys.argv.index("--filepath")
#             input_file = sys.argv[filepath_index + 1]
#         except (ValueError, IndexError):
#             print("Error: --filepath requires a file path.")
#             return
#     if "--char" in sys.argv:
#         try:
#             char_index = sys.argv.index("--char")
#             selected_voice = sys.argv[char_index + 1]
#         except (ValueError, IndexError):
#             print("Error: --char requires a voice name.")
#             return
#     if input_file and selected_voice:
#         print(f"正在处理文件: {input_file} 使用朗读角色配置: {selected_voice}")
#         asyncio.run(process_text_file(input_file, voice=selected_voice))
#     else:
#         print("错误：未提供输入文件路径或朗读角色。请使用 --filepath <file path> 和 --char <voice name> 参数指定。")
# 
# if __name__ == "__main__":
#     # Use the new function to process arguments
#     process_from_args()
# EOL
# python tts.py --filepath "/content/subtitles/word_level_translated.txt" --char "$READ_CHAR_FROM_PYTHON"

import yt_dlp
import requests
import pickle
import json
from pathlib import Path

# Define the output file path
upload_config_file = Path("/content/upload_config.pkl")

# 1. Extract Title using yt-dlp
ydl_opts = {
    'skip_download': True,
    'quiet': True,
    'extractor_args': {
        'youtube': {
            'player_client': ['default', '-web_safari'],
        }
    },
    'remote_components': ['ejs:github'],
}
if 'cookies_file_path' in globals() and cookies_file_path:
    ydl_opts['cookiefile'] = cookies_file_path

with yt_dlp.YoutubeDL(ydl_opts) as ydl:
    info_dict = ydl.extract_info(URL, download=False)
    title = info_dict.get('title', None)
    print(f"Original Title: {title}")

# 2. Load API Config dynamically based on model_name
target_model = globals().get('model_name', 'GLM-4-9B-0414')
api_config = None

try:
    with open("/content/api_setting.json", "r", encoding="utf-8") as f:
        config_data = json.load(f)
    for api in config_data.get("apis", []):
        if api.get("name") == target_model or api.get("model") == target_model:
            api_config = api
            break
except Exception as e:
    print(f"Error loading api_setting.json: {e}")

if not api_config:
    raise ValueError(f"API config for {target_model} not found.")

api_url = api_config['url']
headers = {
    "Content-Type": "application/json",
    "Authorization": f"Bearer {api_config['api_key']}"
}
model_path = api_config['model']

# 3. AI Translation for Title
SYSTEM_PROMPT_TITLE = "# role\n爆款视频up主\n\n## 任务\n将英文标题翻译成吸引眼球的爆款视频中文标题。\n\n## 输出格式\n直接给出翻译后的中文标题"

payload_title = {
    "model": model_path,
    "messages": [
        {"role": "system", "content": SYSTEM_PROMPT_TITLE},
        {"role": "user", "content": title}
    ]
}

res_title = requests.post(api_url, json=payload_title, headers=headers).json()
translated_title = res_title['choices'][0]['message']['content'].replace('**', '').strip()
print(f"Translated Title: {translated_title}")

# 4. AI Tag Generation
SYSTEM_PROMPT_TAGS = "# role\n视频内容标签专家\n\n## 任务\n根据标题生成5个左右中文关键词标签。\n\n## 输出格式\n逗号分隔的关键词列表，例如：关键词1,关键词2,关键词3"

payload_tags = {
    "model": model_path,
    "messages": [
        {"role": "system", "content": SYSTEM_PROMPT_TAGS},
        {"role": "user", "content": translated_title}
    ]
}

res_tags = requests.post(api_url, json=payload_tags, headers=headers).json()
tags_raw = res_tags['choices'][0]['message']['content'].replace('**', '').strip()
tags_list = [tag.strip() for tag in tags_raw.replace('，', ',').split(',') if tag.strip()]
print(f"AI Generated Tags: {tags_list}")

# 5. Save Config
upload_data = {
    'title_desc': '(中配)' + translated_title,
    'tags': tags_list
}

with open(upload_config_file, 'wb') as f:
    pickle.dump(upload_data, f)

print(f"\nConfig saved to {upload_config_file}")

from IPython.display import Audio, display

sound_file = '/content/subtitles/word_level_translated.mp3'

display(Audio(sound_file, autoplay=True))

!pip install -U yt-dlp

import glob
import subprocess
import os

# 1. 清理旧的 MP4 文件
mp4_files = glob.glob('*.mp4')
if mp4_files:
    print("Found .mp4 files. Removing...")
    !rm -f *.mp4
else:
    print("No .mp4 files found.")

#@markdown ## **用yt-dlp模块下载指定url的youtube视频，然后使用ffmpeg替换视频音轨**

# 定义输出文件路径
downloaded_video_base_name = '/content/downloaded_video'
final_video_path = '/content/final_video.mp4'
new_audio_path = '/content/subtitles/word_level_translated.mp3'

# 检查音频文件是否存在
if not os.path.exists(new_audio_path):
    print(f"Error: New audio file not found at {new_audio_path}")
else:
    # --- 步骤 1: 使用 yt-dlp 命令行下载视频 ---
    print(f"Downloading video from URL: {URL}")

    # 检查 Deno 是否存在
    deno_path = '/root/.deno/bin/deno'
    if not os.path.exists(deno_path):
        print(f"警告: 在 {deno_path} 未找到 Deno。JS 解密可能会失败。")
    else:
        print(f"Deno 路径确认: {deno_path}")

    # 构建命令参数列表
    cmd = [
        'python', '-m', 'yt_dlp',
        '-f', 'bestvideo+bestaudio/best', # 下载最佳画质
        '--extractor-args', 'youtube:player_client=default,-web_safari', # GitHub 核心修复
        '--remote-components', 'ejs:github',     # 下载解密脚本
                # 指定 Deno
        '--no-playlist',
        '-o', f'{downloaded_video_base_name}.%(ext)s',
        URL
    ]

    # 检查 cookies 文件是否存在（如果文件不存在，yt-dlp 会报错退出）
    if 'cookies_file_path' in locals() and cookies_file_path:
        if os.path.exists(cookies_file_path):
            cmd.extend(['--cookies', cookies_file_path])
            print(f"使用 Cookies 文件: {cookies_file_path}")
        else:
            print(f"警告: Cookies 文件 {cookies_file_path} 不存在，将不使用 Cookies 下载。")

    print("正在执行命令...")
    actual_downloaded_video_path = None
    try:
        # 【关键修改】capture_output=True 用于捕获报错信息
        result = subprocess.run(cmd, check=True, capture_output=True, text=True)

        # 打印 yt-dlp 的正常输出
        if result.stdout:
            print(result.stdout)

        # 查找实际下载的文件
        downloaded_files = glob.glob(f'{downloaded_video_base_name}.*')
        if downloaded_files:
            actual_downloaded_video_path = downloaded_files[0]
            print(f"Video downloaded successfully to {actual_downloaded_video_path}")
        else:
            raise FileNotFoundError(f"yt-dlp did not download a file matching {downloaded_video_base_name}.*")

        # --- 步骤 2: 使用 ffmpeg 替换音轨 ---
        print(f"Replacing audio track in {actual_downloaded_video_path} with {new_audio_path}")
        subprocess.run(['ffmpeg', '-y', '-i', actual_downloaded_video_path, '-i', new_audio_path,
                        '-c:v', 'copy', '-c:a', 'aac', '-map', '0:v:0', '-map', '1:a:0',
                        final_video_path], check=True)

        print(f"Audio replacement complete. Final video saved to {final_video_path}")

        # --- 清理 ---
        if actual_downloaded_video_path and os.path.exists(actual_downloaded_video_path):
            os.remove(actual_downloaded_video_path)
            print(f"Removed temporary video file: {actual_downloaded_video_path}")

    except subprocess.CalledProcessError as e:
        # 打印详细报错信息
        print("\n!!! 下载过程出错 !!!")
        print(f"错误代码: {e.returncode}")
        print("--- 标准输出 ---")
        print(e.stdout)
        print("--- 错误输出 ---")
        print(e.stderr)

    except FileNotFoundError as e:
        print(f"Error: {e}. Make sure ffmpeg is installed or yt-dlp downloaded a file.")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")

#@markdown ## **下载视频封面**

# prompt: 用yt-dlp模块下载指定URL视频的封面，并保持为cover.png

#URL='https://www.youtube.com/watch?v=gmDcUsBzAZ4' # Replace with the actual YouTube URL

# Use yt-dlp to download the thumbnail
ydl_opts_thumbnail = {
    'skip_download': True, # Only extract info, don't download video/audio
    'writethumbnail': True, # Write the thumbnail image
    'outtmpl': '/content/cover.%(ext)s', # Output path template for the thumbnail
    'noplaylist': True, # Ensure only the single video is processed
}

# Add cookiefile option if cookies are available
if cookies_file_path:
    ydl_opts_thumbnail['cookiefile'] = cookies_file_path

print(f"Downloading thumbnail for URL: {URL}")
try:
    with yt_dlp.YoutubeDL(ydl_opts_thumbnail) as ydl:
        info_dict = ydl.extract_info(URL, download=True)
        # yt-dlp automatically saves the thumbnail with the specified outtmpl and correct extension
    print(f"Thumbnail downloaded successfully to /content/cover.png (or similar extension)")

except yt_dlp.DownloadError as e:
    print(f"Error during thumbnail download: {e}")
except Exception as e:
    print(f"An unexpected error occurred: {e}")

#@markdown ## **压缩封面，提高上传成功率**
from PIL import Image
import os

def convert_and_compress_to_jpeg(input_path, output_path, target_size_kb=50):
    """
    Converts an image to JPEG format and adjusts quality to be under target_size_kb,
    keeping the original dimensions.

    Args:
        input_path (str): Path to the input image file.
        output_path (str): Path to save the output JPEG file.
        target_size_kb (int): Target file size in kilobytes.
    """
    if not os.path.exists(input_path):
        print(f"Error: Input file not found at {input_path}")
        return

    try:
        with Image.open(input_path) as img:
            # Ensure image is in RGB mode before saving as JPEG
            if img.mode != 'RGB':
                img = img.convert('RGB')

            # Initial quality and size check
            quality = 90
            img.save(output_path, 'jpeg', quality=quality)
            current_size_kb = os.path.getsize(output_path) / 1024

            # Adjust quality if necessary
            while current_size_kb > target_size_kb and quality > 4:
                quality -= 5
                img.save(output_path, 'jpeg', quality=quality)
                current_size_kb = os.path.getsize(output_path) / 1024
                print(f"Current size: {current_size_kb:.2f} KB with quality {quality}")

            if current_size_kb <= target_size_kb:
                print(f"Successfully converted and compressed to {output_path} with size {current_size_kb:.2f} KB")
            else:
                print(f"Warning: Could not compress {input_path} to under {target_size_kb} KB. Final size is {current_size_kb:.2f} KB.")

    except FileNotFoundError:
        print("Error: PIL library not found. Please install it.")
    except Exception as e:
        print(f"An error occurred during conversion: {e}")

# Define input and output paths
input_path = '/content/cover.webp'
output_path = '/content/cover.jpeg'

# Convert and compress the image
convert_and_compress_to_jpeg(input_path, output_path, target_size_kb=50)

!pip3 install bilibili-api-python
!pip3 install aiohttp

# Commented out IPython magic to ensure Python compatibility.
# %%shell
# cd /content
# cat <<EOL > VideoUploader.py
# 
# from bilibili_api import sync, video_uploader, Credential
# from pathlib import Path
# import pickle
# import time # Import time for delays
# 
# async def main():
#     credential = Credential(sessdata="ea190ee2%2C1796896176%2Cb606e%2A62CjBw1YSiKJvXsfXJY2sBBnLMKPxUvCDA_I4_AayJi4vrvN46tWkObCKwOSkixyjv7IESVmhrejlac1dvMnFia0lTRU1yNFd6N3o5d1JsX29Ic0p1MERCSHpyRVRHSUhkU3NQWGtVanp3cHNYMFBUOElTaFlBbjNSM2owOXo5Vk1ZUUhCQ3NqS1lRIIEC", bili_jct="4e70db5c44b67e6270534555e39d9d4e", buvid3="0D6A5D9C-847E-4483-2628-A8AC0E4025BB84659infoc")
#     # 具体请查阅相关文档和 VideoMeta 内代码注释
#     # 建议使用 VideoMeta 类来构建 meta 信息，避免参数错误，但也兼容直接传入 dict
#     # meta = {
#     #     "act_reserve_create": 0,
#     #     "copyright": 1,
#     #     "source": "",
#     #     "desc": "",
#     #     "desc_format_id": 0,
#     #     "dynamic": "",
#     #     "interactive": 0,
#     #     "no_reprint": 1,
#     #     "open_elec": 0,
#     #     "origin_state": 0,
#     #     "subtitles": {
#     #         "lan": "",
#     #         "open": 0
#     #     },
#     #     "tag": "音乐,音乐综合",
#     #     "tid": 130,
#     #     "title": "title",
#     #     "up_close_danmaku": False,
#     #     "up_close_reply": False,
#     #     "up_selection_reply": False,
#     #     "dtime": 0
#     # }
#     # vu_porden_meta = video_uploader.VideoPorderMeta(video_uploader.VideoPorderType.FIREWORK) # 商单参数
# 
#     # --- Reading and Re-assigning from the file ---
# 
#     # Initialize variables to None or default values
#     loaded_title_desc = None
#     loaded_tags = None
# 
# 
#     # Check if the file exists and load the data
#     upload_config_file = Path("/content/upload_config.pkl")
#     if upload_config_file.exists():
#         try:
#             with open(upload_config_file, 'rb') as f:
#                 loaded_data = pickle.load(f)
# 
#             loaded_title_desc = loaded_data.get('title_desc')
#             loaded_tags = loaded_data.get('tags')
# 
#             print(f"\nConfiguration loaded from {upload_config_file}:")
#             print(f"Loaded Title/Desc: {loaded_title_desc}")
#             print(f"Loaded Tags: {loaded_tags}")
# 
#             # Re-assign the variables
#             title_desc = loaded_title_desc
#             tags = loaded_tags
# 
#             print("\nVariables 'title_desc' and 'tags' have been re-assigned with loaded data.")
# 
#         except FileNotFoundError:
#             print(f"\nError: Configuration file not found at {upload_config_file}")
#         except Exception as e:
#             print(f"\nError loading configuration: {e}")
#     else:
#         print(f"\nConfiguration file not found at {upload_config_file}. Skipping load.")
# 
#     vu_meta = video_uploader.VideoMeta(
#         tid=130,
#         title=loaded_title_desc,
#         tags=loaded_tags,
#         desc=loaded_title_desc,
#         cover="/content/cover.jpeg",
#         no_reprint=True,
#     )
#     # await vu_meta.verify(credential=credential) # 本地预检 meta 信息，出错则抛出异常
#     page = video_uploader.VideoUploaderPage(
#         path="/content/final_video.mp4",
#         title=loaded_title_desc,
#         description=loaded_title_desc,
#     )
#     uploader = video_uploader.VideoUploader(
#         [page], vu_meta, credential,line=video_uploader.Lines.QN
#     )  # 选择七牛线路，不选则自动测速选择最优线路
#     # uploader = video_uploader.VideoUploader([page], meta, credential, cover='cover.png')
#     # # meta 直接传入 dict 则需要在 video_uploader.VideoUploader 传入封面
# 
#     @uploader.on("__ALL__")
#     async def ev(data):
#         print(data)
# 
#     await uploader.start()
# 
# 
# max_upload_retries = 6
# upload_retry_count = 0
# while upload_retry_count < max_upload_retries:
#     try:
#         sync(main())
#         print("\nVideo upload completed successfully.")
#         break # Exit the loop if upload is successful
#     except Exception as e:
#         upload_retry_count += 1
#         print(f"\nError during video upload: {e}")
#         if upload_retry_count < max_upload_retries:
#             delay = 10 * (2 ** (upload_retry_count - 1)) # Exponential backoff delay
#             print(f"Retrying upload (Attempt {upload_retry_count}/{max_upload_retries}). Waiting for {delay} seconds...")
#             time.sleep(delay)
#         else:
#             print(f"Max upload retries ({max_upload_retries}) reached. Upload failed.")
# 
# EOL

#@markdown ## 是否上传B站
IsUploadingBzhan = True #@param {type:'boolean'}
if IsUploadingBzhan:
  !python VideoUploader.py